### PR TITLE
Service and Facade Implementation: Troop

### PR DESCRIPTION
**Pull request by DanoFecko**
* Troop Service
* Troop Service Impl
* Troop Facade Impl
* made changes to TroopDao (added 2 missing methods)

### CODE REVIEW

**Comment by GreenManSK** [comment]
Need tests for new methods in TroopDao

**Comment by GreenManSK** [comment]
More tests for new methods TroopDao are needed. All tests in for Dao have to be on the same level as were tests in the 1st milestone. This will be needed for the final evaluation of the project.

**Comment by GreenManSK** [comment]
Aslo add Troop entity to TroopDTO mapping to DozerCustomConfig in ServiceConfiguration

**Comment by DanoFecko** [comment]
@GreenManSK I have made requested changes

**Pull request merged**
